export const USER_UP_BLOG_REQUEST = "USER_UP_BLOG_REQUEST";
export const USER_UP_BLOG_SUCCESS = "USER_UP_BLOG_SUCCESS";
export const USER_UP_BLOG_FAIL = "USER_UP_BLOG_FAIL";

export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";
export const BLOG_LIST_FAIL = "BLOG_LIST_FAIL";
